### ISSUE TITLE
couldn't find pretrained model when inference

### ISSUE THREAD

**Issue by yhd-ai** [damo-cv/RealisDance#12]
Hi, I followed your readme instructions and tried to run the inference script. And I got this error
`python inference.py --config configs/stage2_hamer.yaml --smpl __assets__/demo_seq/smpl_1.mp4     --hamer __assets__/demo_seq/hamer_1.mp4 --dwpose __assets__/demo_seq/dwpose_1.pkl     --ckpt /data0/lg2/RealisDance/pretrained_models/stage_2_hamer_release.ckpt --ref /data0/public_dataset/neuman_data/data/neuman/dataset/bike/4d_humans/images/image_0000.png --output /data0/lg2/RealisDance/output
09/26/2024 16:55:22 - INFO - root - Load scheduler, tokenizer and models.
Traceback (most recent call last):
  File "/home/lg2/.conda/envs/realdance/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 379, in load_config
    config_file = hf_hub_download(
  File "/home/lg2/.conda/envs/realdance/lib/python3.10/site-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "/home/lg2/.conda/envs/realdance/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "/home/lg2/.conda/envs/realdance/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'pretrained_models/RV/rv-5-1'. Use `repo_type` argument if needed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data0/lg2/RealisDance/inference.py", line 339, in <module>
    main(**exp_config)
  File "/data0/lg2/RealisDance/inference.py", line 181, in main
    vae = AutoencoderKL.from_pretrained(pretrained_model_path, subfolder="vae")
  File "/home/lg2/.conda/envs/realdance/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/lg2/.conda/envs/realdance/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 612, in from_pretrained
    config, unused_kwargs, commit_hash = cls.load_config(
  File "/home/lg2/.conda/envs/realdance/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/lg2/.conda/envs/realdance/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 415, in load_config
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like pretrained_models/RV/rv-5-1 is not the path to a directory containing a config.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.`

**Comment by theFoxofSky** [comment]
rv-5-1 is here https://huggingface.co/SG161222/Realistic_Vision_V5.1_noVAE/tree/main. Please download it an link it to the corresponding location "pretrained_models/RV/rv-5-1"

**Comment by yhd-ai** [comment]
should I download all or only "Realistic_Vision_V5.1.ckpt"?

**Comment by yhd-ai** [comment]
Thanks！
