### ISSUE TITLE
prepare_pose code maybe wrong

### ISSUE THREAD

**Issue by HW140701** [damo-cv/RealisDance#22]
When I tested it with reference to the prepare_pose/README.md document, the following error occurred when I ran DWPose

```python
Traceback (most recent call last):
  File "inference_video.py", line 23, in <module>
    pose = DWposeDetector()
  File "/home/huangwang/git/RealisDance_new/RealisDance/prepare_pose/DWPose/ControlNet-v1-1-nightly/annotator/dwpose/__init__.py", line 35, in __init__
    self.pose_estimation = Wholebody()
  File "/home/huangwang/git/RealisDance_new/RealisDance/prepare_pose/DWPose/ControlNet-v1-1-nightly/annotator/dwpose/wholebody.py", line 16, in __init__
    self.session_det = ort.InferenceSession(path_or_bytes=onnx_det, providers=providers)
  File "/home/huangwang/miniforge3/envs/DWPose_control-v11/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/huangwang/miniforge3/envs/DWPose_control-v11/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 480, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from ControlNet-v1-1-nightly/annotator/ckpts/yolox_l.onnx failed:Load model ControlNet-v1-1-nightly/annotator/ckpts/yolox_l.onnx failed. File doesn't exist
```

I checked the original code of the DWPose repo and found that the weight path in whole_body.py is different.
so I want to ask, is this prepare_pose reviewed or checked?

**Comment by theFoxofSky** [comment]
Please check this issue @Wangbenzhi

**Comment by Cccccz-x** [comment]
> When I tested it with reference to the prepare_pose/README.md document, the following error occurred when I ran DWPose
> 
> ```python
> Traceback (most recent call last):
>   File "inference_video.py", line 23, in <module>
>     pose = DWposeDetector()
>   File "/home/huangwang/git/RealisDance_new/RealisDance/prepare_pose/DWPose/ControlNet-v1-1-nightly/annotator/dwpose/__init__.py", line 35, in __init__
>     self.pose_estimation = Wholebody()
>   File "/home/huangwang/git/RealisDance_new/RealisDance/prepare_pose/DWPose/ControlNet-v1-1-nightly/annotator/dwpose/wholebody.py", line 16, in __init__
>     self.session_det = ort.InferenceSession(path_or_bytes=onnx_det, providers=providers)
>   File "/home/huangwang/miniforge3/envs/DWPose_control-v11/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 419, in __init__
>     self._create_inference_session(providers, provider_options, disabled_optimizers)
>   File "/home/huangwang/miniforge3/envs/DWPose_control-v11/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 480, in _create_inference_session
>     sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
> onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from ControlNet-v1-1-nightly/annotator/ckpts/yolox_l.onnx failed:Load model ControlNet-v1-1-nightly/annotator/ckpts/yolox_l.onnx failed. File doesn't exist
> ```
> 
> I checked the original code of the DWPose repo and found that the weight path in whole_body.py is different. so I want to ask, is this prepare_pose reviewed or checked?

If you've placed the file correctly and it still doesn't work, just use the absolute path

**Comment by Wangbenzhi** [comment]
thanks for your feedbeek, fixed.

**Comment by HW140701** [comment]
prepare_pose code have too many error, I guess you haven't pulled your own code and actually run it.

**Comment by theFoxofSky** [comment]
@Wangbenzhi
